### ISSUE TITLE
Which API to use for getting data?

### ISSUE THREAD

**Issue by fredrikj31** [Philipnah/ego#1]
Has there been made a decision on which API, we should use to fetch electricity and carbon emission data from?

If not, I think we should think about these parameters, when we pick the API.
- [ ] Monthly price for the API (hopefully they have a free tier)
- [ ] Should the API have data for multiple countries?
- [ ] If we want to support multiple APIs (for multiple providers), we also need multiple parsers to parse API responses

I have found a few options, which has a free tier, and where we can get data from.
- [Energi Data Service](https://www.energidataservice.dk/). I think this only have data from Danish energy sources
- [Energy-Charts](https://energy-charts.info/api.html?l=de&c=DE). German energy provider
- [FlatPeak](https://flatpeak.com). Multiple energy sources, but doesn't have a free tier 😢 
- [Rapid API](https://rapidapi.com/miesolavi/api/electricity-price) Maybe have a free tier.
  - [Rapid API 2](https://rapidapi.com/miesolavi/api/co2-emissions) Same author, but with CO2 emissions

What do you think?

**Comment by Philipnah** [comment]
The API used for getting the electricity emissions data is Energi Data Service. In the future it will also be used for getting the electricity prices. For now, only Denmark is supported.
Thank you for your thoughts and research! 🎉
